version: 2.1
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  test:
    docker:
      - image: circleci/node # the primary container, where your job's commands are run
    parallelism: 4
    steps:
      - run:
          command: |
            for (( i=1; i<=5; i++ ))
            do
              echo "Running unit test $i"
            done
      - run:
          command: |
            for (( i=6; i<=10; i++ ))
            do
              echo "Running unit test $i"
            done
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test
